# Generated by Django 6.0.4 on 2026-04-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('violence', 'Violence'), ('weapon', 'Weapon'), ('non_violence', 'Non Violence')], max_length=20)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alerts/images/')),
                ('clip', models.FileField(blank=True, null=True, upload_to='alerts/clips/')),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
